import { Category, Product } from '../types/shop';

export const CATEGORIES: Category[] = [
  'All',
  'Engine',
  'Brakes',
  'Lighting',
  'Accessories',
  'Tires',
];

export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Brembo Venting Brake Rotor (Front)',
    brand: 'Brembo',
    category: 'Brakes',
    price: 145.00,
    originalPrice: 193.33,
    rating: 4.9,
    reviewCount: 342,
    image: '/shop/ShopImages/brembobrakerotor.webp',
    inStock: true,
    badge: 'Best Seller',
    description: 'High performance venting brake rotor engineered for precision.',
    tags: ['performance', 'rotor', 'brakes'],
  },
  {
    id: '2',
    name: 'Brembo Premium Ceramic Brake Pads Set',
    brand: 'Brembo',
    category: 'Brakes',
    price: 89.99,
    originalPrice: 126.75,
    rating: 4.7,
    reviewCount: 218,
    image: '/shop/ShopImages/Ceramicpads.webp',
    inStock: true,
    description: 'Ultra-high-performance ceramic brake pads.',
    tags: ['ceramic', 'pads', 'brakes'],
  },
  {
    id: '3',
    name: 'Brembo High-Performance Brake Caliper (Red)',
    brand: 'Brembo',
    category: 'Brakes',
    price: 299.00,
    rating: 4.8,
    reviewCount: 156,
    image: '/shop/ShopImages/FrontBrakeKit.jpeg',
    inStock: true,
    badge: 'New',
    description: 'High-performance red brake caliper.',
    tags: ['performance', 'caliper', 'brakes'],
  },
  {
    id: '4',
    name: 'Brembo Sport DOT 4 Brake Fluid (1L)',
    brand: 'Brembo',
    category: 'Brakes',
    price: 24.50,
    originalPrice: 30.25,
    rating: 4.6,
    reviewCount: 489,
    image: '/shop/ShopImages/brakefluid.webp',
    inStock: true,
    description: 'Sport DOT 4 brake fluid for high performance systems.',
    tags: ['fluid', 'dot4', 'brakes'],
  },
  {
    id: '5',
    name: 'Bosch Front Disc',
    brand: 'Bosch',
    category: 'Brakes',
    price: 39.99,
    rating: 4.5,
    reviewCount: 731,
    image: '/shop/ShopImages/BoshForntdisc.jpeg',
    inStock: false,
    description:
      'Aerodynamic beam wiper blades with pressure-optimized design for streak-free visibility in all weather.',
    tags: ['all-season', 'beam-design', 'aerodynamic'],
  },
  {
    id: '6',
    name: 'Iridium Spark Plugs (Set of 4)',
    brand: 'NGK',
    category: 'Engine',
    price: 54.99,
    originalPrice: 69.99,
    rating: 4.8,
    reviewCount: 267,
    image: '/shop/ShopImages/images.jpeg',
    inStock: true,
    badge: 'Sale',
    description:
      'Fine-wire iridium centre electrode for exceptional ignitability and 100,000-mile service life.',
    tags: ['iridium', 'long-life', 'fuel-efficient'],
  },
  {
    id: '7',
    name: 'Performance Air Intake System',
    brand: 'K&N',
    category: 'Engine',
    price: 189.99,
    rating: 4.9,
    reviewCount: 412,
    image: '/shop/ShopImages/AirIntake.jpeg',
    inStock: true,
    badge: 'Premium',
    description:
      'Pilot Sport A/S 4 with Hybrid Electric Technology for outstanding grip in wet and dry conditions.',
    tags: ['all-season', 'performance', 'ev-compatible'],
  },
  {
    id: '8',
    name: 'Auto Accessories Bundle',
    brand: 'Automate',
    category: 'Accessories',
    price: 149.99,
    originalPrice: 199.99,
    rating: 4.7,
    reviewCount: 189,
    image: '/shop/ShopImages/shopping.webp',
    inStock: true,
    description:
      'Professional-grade Bluetooth OBD-II scanner with real-time diagnostics, fault code reading, and live data.',
    tags: ['bluetooth', 'wireless', 'professional'],
  },
];
