import { Category, Product } from '../types/shop';

export const CATEGORIES: Category[] = [
  'All',
  'Engine',
  'Brakes',
  'Lighting',
  'Accessories',
  'Tires',
];

export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Premium Ceramic Brake Pads',
    brand: 'Brembo',
    category: 'Brakes',
    price: 89.99,
    originalPrice: 119.99,
    rating: 4.9,
    reviewCount: 342,
    image: '/shop/brake-pads.jpg',
    inStock: true,
    badge: 'Best Seller',
    description:
      'Ultra-high-performance ceramic brake pads engineered for precision stopping power and zero fade under extreme conditions.',
    tags: ['ceramic', 'performance', 'low-dust'],
  },
  {
    id: '2',
    name: 'High-Flow Engine Oil Filter',
    brand: 'Bosch',
    category: 'Engine',
    price: 24.99,
    originalPrice: 34.99,
    rating: 4.7,
    reviewCount: 218,
    image: '/shop/oil-filter.jpg',
    inStock: true,
    badge: 'Sale',
    description:
      'Advanced multi-layer filtration media captures 99.6% of harmful contaminants, extending engine life dramatically.',
    tags: ['filtration', 'engine-protection', 'oem-quality'],
  },
  {
    id: '3',
    name: 'LED Matrix Headlight Kit',
    brand: 'Philips',
    category: 'Lighting',
    price: 249.99,
    rating: 4.8,
    reviewCount: 156,
    image: '/shop/led-headlight.jpg',
    inStock: true,
    badge: 'New',
    description:
      'Next-generation LED matrix headlights with adaptive beam control and 300% brighter output than halogen.',
    tags: ['led', 'adaptive', 'plug-and-play'],
  },
  {
    id: '4',
    name: 'Performance Air Filter',
    brand: 'K&N',
    category: 'Engine',
    price: 64.99,
    originalPrice: 79.99,
    rating: 4.6,
    reviewCount: 489,
    image: '/shop/air-filter.jpg',
    inStock: true,
    description:
      'Washable and reusable high-flow air filter for maximum airflow and horsepower gains up to 8 HP.',
    tags: ['reusable', 'high-flow', 'washable'],
  },
  {
    id: '5',
    name: 'Beam Wiper Blade Set',
    brand: 'Bosch',
    category: 'Accessories',
    price: 39.99,
    rating: 4.5,
    reviewCount: 731,
    image: '/shop/wiper-blades.jpg',
    inStock: false,
    description:
      'Aerodynamic beam wiper blades with pressure-optimized design for streak-free visibility in all weather.',
    tags: ['all-season', 'beam-design', 'aerodynamic'],
  },
  {
    id: '6',
    name: 'Iridium Spark Plugs (Set of 4)',
    brand: 'NGK',
    category: 'Engine',
    price: 54.99,
    originalPrice: 69.99,
    rating: 4.8,
    reviewCount: 267,
    image: '/shop/spark-plugs.jpg',
    inStock: true,
    badge: 'Sale',
    description:
      'Fine-wire iridium centre electrode for exceptional ignitability and 100,000-mile service life.',
    tags: ['iridium', 'long-life', 'fuel-efficient'],
  },
  {
    id: '7',
    name: 'All-Season Performance Tires',
    brand: 'Michelin',
    category: 'Tires',
    price: 189.99,
    rating: 4.9,
    reviewCount: 412,
    image: '/shop/tires.jpg',
    inStock: true,
    badge: 'Premium',
    description:
      'Pilot Sport A/S 4 with Hybrid Electric Technology for outstanding grip in wet and dry conditions.',
    tags: ['all-season', 'performance', 'ev-compatible'],
  },
  {
    id: '8',
    name: 'Smart OBD-II Diagnostic Scanner',
    brand: 'Autel',
    category: 'Accessories',
    price: 149.99,
    originalPrice: 199.99,
    rating: 4.7,
    reviewCount: 189,
    image: '/shop/obd-scanner.jpg',
    inStock: true,
    description:
      'Professional-grade Bluetooth OBD-II scanner with real-time diagnostics, fault code reading, and live data.',
    tags: ['bluetooth', 'wireless', 'professional'],
  },
];
